In [5]:
pressures = [0.11,0.12,0.13,0.14,0.15]

In [6]:
pressures.append(0.16)
pressures

[0.11, 0.12, 0.13, 0.14, 0.15, 0.16]

In [7]:
result = pressures.append([0.17,0.18])

In [8]:
result

In [10]:
# first time: [1, 3, 5]
# second time: [3, 5]

values = []
values.append(1)
values.append(3)
values.append(5)
print('first time:', values)
#values = values[1:]
del values[0] # not a function just a statement
print('second time:', values)

first time: [1, 3, 5]
second time: [3, 5]


In [11]:
letters = list('gold')
result = sorted(letters)
print('letters is', letters, 'and result is', result)

letters is ['g', 'o', 'l', 'd'] and result is ['d', 'g', 'l', 'o']


In [12]:
s = 'software carpentry'
list6 = list(s)
list6


['s',
 'o',
 'f',
 't',
 'w',
 'a',
 'r',
 'e',
 ' ',
 'c',
 'a',
 'r',
 'p',
 'e',
 'n',
 't',
 'r',
 'y']

In [14]:
letters = list('gold')
result = letters.sort() # 
print('letters is', letters, 'and result is', result) # output of a method to a value is not meaningful

letters is ['d', 'g', 'l', 'o'] and result is None


In [15]:
element = 'fluorine'
print(element[::2])
print(element[::-1])

furn
eniroulf


## .tab explains all the possible methods in the datatype

Python is indentation oriented.

In [17]:
letters.index('g')

1

In [19]:
for i in [1,2,3]:
    print(i)    
print('Done')

1
2
3
Done


In [21]:
primes = [2,3,5]
for i in primes:
    squared = i**2
    cubed = i**3
    print(i,squared,cubed)

2 4 8
3 9 27
5 25 125


In [23]:
for counter in range(0,11,3):
    print(counter)

0
3
6
9


In [28]:
list7 = list(range(0,6))
type(list7)
list7

[0, 1, 2, 3, 4, 5]

In [35]:
original = "tin"
result = ''
for char in original:
    result = char + result 
print(result)

nit


In [36]:
data = [1,2,2,5]
cumulative = []
sum = 0
for number in data:
    sum += number
    cumulative += [sum]
print(cumulative)

[1, 3, 5, 10]


In [37]:
# List of word lengths: ["red", "green", "blue"] => [3, 5, 4]
lengths = []
for word in ["red", "green", "blue"]:
    lengths.append(len(word))
print(lengths)

[3, 5, 4]


In [47]:
# Concatenate all words: ["red", "green", "blue"] => "redgreenblue"
words = ["red", "green", "blue"]
result = ''
for word in words:
    result = result + word
print(result)

redgreenblue


In [52]:
num = [1,-5,0]
for i in range(len(num)):
    if num[i] > 0:
        print('positive')
    elif num[i] == 0:
        print('zero')
    else:
        print('negative')

positive
negative
zero


In [54]:
grade = 85 # use paranthesis as much as you can
if grade >= 70 and grade < 80: # and is a keyword combining logical statements
    print('grade is C')
elif grade >= 80:
    print('grade is B')
elif grade >= 90:
    print('grade is A')

grade is B


In [55]:
listofnumbers = list(range(0,11))
for i in listofnumbers:
    if i == 5: # equality with double equals
        print('found five')
    else:
        print('did not find')
        
            

did not find
did not find
did not find
did not find
did not find
found five
did not find
did not find
did not find
did not find
did not find


In [56]:
# [0, 1, 1, 1, 0, 1]

original = [-1.5, 0.2, 0.4, 0.0, -1.3, 0.4]
result = []
for value in original:
    if value < 0:
        result.append(0)
    else:
        result.append(1)
print(result)

[0, 1, 1, 1, 0, 1]


In [57]:
values = [-2,1,65,78,-54,-24,100]
smallest, largest = None, None
for v in values:
    if smallest==None and largest==None:
        smallest, largest = v, v
    else:
        smallest = min(smallest, v)
        largest = max(largest, v)
print(smallest, largest)

-54 100


In [1]:
import math

In [2]:
print(math.pi)

3.141592653589793


In [3]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [4]:
math.sqrt(2)

1.4142135623730951

In [5]:
math.pow(2,0.5)

1.4142135623730951

In [6]:
bases = 'ACTTGCTTGC'

In [7]:
import random

random.choice(bases)

'C'

# Functions

In [9]:
def print_greeting():
    print('Hello')

In [10]:
print_greeting()

Hello


In [11]:
print_greeting

<function __main__.print_greeting>

In [16]:
def print_date(year,month,date):
    joined = str(date) + "/" + str(month) + "/" + str(year)
    print(joined)

In [17]:
print_date(1988,4,29)

29/4/1988


In [27]:
def average(values):
    if len(values) == 0:
        return None
    return sum(values)/len(values)

In [29]:
print(average([]))

None


In [30]:
print(print_greeting())

Hello
None


In [31]:
def another_function():
    print("Syntax errors are annoying.")
    print("But at least python tells us about them!")
    print("So they are usually not too hard to fix.")

In [32]:
another_function()

Syntax errors are annoying.
But at least python tells us about them!
So they are usually not too hard to fix.


In [37]:
def report(pressure):
    print('pressure is', pressure)

print('calling', report(22.5))

pressure is 22.5
calling None


In [38]:
def first_negative(values):
    for v in values:
        if(len(values) == 0):
            return None
        elif (v < 0):
            return v

In [41]:
values = []
first_negative(values)

# Scope

Variables defined within a function is available only within the function

In [45]:
pressure = 103.9

def adjust(t):
    temperature = t * 1.43 / pressure
    return temperature

In [46]:
adjust(0.9)

0.01238691049085659

In [47]:
limit = 100

def clip(value):
    return min(max(0.0,value),limit)

value = -22.5
print(clip(value))

0.0


## error is quite informative

# Numpy

In [48]:
import numpy as np

In [52]:
data = np.loadtxt(fname = 'C:/Users/parva/Downloads/data/inflammation-01.csv', delimiter = ',')

In [53]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [63]:
data[20:30,20:30]

array([[18., 19.,  9.,  6., 11., 12.,  7.,  6.,  3.,  6.],
       [12., 10., 16.,  7., 14., 12.,  5.,  4.,  6.,  9.],
       [16., 15., 13.,  6., 12.,  9., 10.,  3.,  3.,  7.],
       [14., 13.,  5., 13.,  7., 14.,  9., 10.,  5., 11.],
       [17., 16.,  5., 10., 10., 15.,  7.,  5.,  3., 11.],
       [ 7., 11., 14.,  7., 13., 11.,  7., 12., 12.,  7.],
       [ 9., 12., 18., 14., 16., 12.,  3., 11.,  3.,  2.],
       [15., 13.,  7., 17.,  4.,  5., 11.,  4.,  8.,  7.],
       [20., 18.,  9.,  5.,  4.,  7., 14.,  8.,  4.,  3.],
       [14., 15., 17.,  4., 14., 13.,  4.,  4., 12., 11.]])

In [55]:
print(type(data))

<class 'numpy.ndarray'>


In [56]:
print(data.dtype)

float64


In [57]:
print(data.shape)

(60, 40)


In [62]:
print('A value in data:', data[20,20])

A value in data: 18.0


In [65]:
print(data[-2:,-4:] * 4)

[[ 8.  0.  8.  0.]
 [12.  4.  4.  0.]]


## all mathematical operations go element wise in numpy array

In [67]:
np.mean(data)

6.14875

In [68]:
maxval, minval, stdval = np.max(data), np.min(data), np.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [69]:
patient_0 = data[0,:]

In [70]:
print(np.max(patient_0))

18.0
